import React, { FunctionComponent } from "react";
import {} from "@material-ui/core/styles";
import { Box, Divider, Typography } from "@material-ui/core";
import { LinkNoDecor } from "../../components/commons/link";
import { PrimaryButton } from "../../components/commons/button";
import { Title } from "../../components/commons/title";

const Text: FunctionComponent = (props) => (
  <Box pb={2}>
    <Typography variant="body1">{props.children}</Typography>
  </Box>
);

const Home: FunctionComponent = () => {
  return (
    <Box p={5}>
      <Title>The problem with poor air quality</Title>

      <Text>
        Poor air quality is one of the largest public health threats of our
        time. Air pollution is the 4th largest risk factor to human health on
        the planet. According to the World Health Organization, more than 90% of
        the world breathes unhealthy air, and air pollution disproportionately
        affects those in developing countries.
      </Text>

      <Title>Air Pollutants</Title>
      <Text>
        The World Health Organization (WHO) reports on six major air pollutants,
        namely particle pollution, ground-level ozone, carbon monoxide, sulfur
        oxides, nitrogen oxides, and lead. Air pollution can have a disastrous
        effect on all components of the environment, including groundwater,
        soil, and air. Additionally, it poses a serious threat to living
        organisms. In this vein, our interest is mainly to focus on these
        pollutants, as they are related to more extensive and severe problems in
        human health and environmental impact. Acid rain, global warming, the
        greenhouse effect, and climate changes have an important ecological
        impact on air pollution.
      </Text>

      <Title>Particulate Matter (PM) and Health</Title>
      <Text>
        Studies have shown a relationship between particulate matter (PM) and
        adverse health effects, focusing on either short-term (acute) or
        long-term (chronic) PM exposure. Particulate matter (PM) is usually
        formed in the atmosphere as a result of chemical reactions between the
        different pollutants. The penetration of particles is closely dependent
        on their size. Particulate Matter (PM) was defined as a term for
        particles by the United States Environmental Protection Agency.
        Particulate matter (PM) pollution includes particles with diameters of
        10 micrometers (μm) or smaller, called PM10, and extremely fine
        particles with diameters that are generally 2.5 micrometers (μm) and
        smaller.
      </Text>

      <Title>Effect of Air Pollution on Health</Title>
      <Text>
        The most common air pollutants are ground-level ozone and Particulates
        Matter (PM). Air pollution is distinguished into two main types: Outdoor
        pollution is the ambient air pollution. Indoor pollution is the
        pollution generated by household combustion of fuels. People exposed to
        high concentrations of air pollutants experience disease symptoms and
        states of greater and lesser seriousness. These effects are grouped into
        short- and long-term effects affecting health. Susceptible populations
        that need to be aware of health protection measures include old people,
        children, and people with diabetes and predisposing heart or lung
        disease, especially asthma. Poor air quality can irritate the eyes,
        nose, and throat, cause shortness of breath, aggravate asthma and other
        respiratory conditions, and affect the heart and cardiovascular system.
        Breathing polluted air for long periods of time can cause more serious
        problems.
      </Text>

      <Divider />

      <Box
        p={4}
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
      >
        <Title align="center">
          See the latest air quality measurements by your country, city, stations...
        </Title>
        <LinkNoDecor to="/measurements">
          <PrimaryButton size="large">
            Let's see
          </PrimaryButton>
        </LinkNoDecor>
      </Box>
    </Box>
  );
};

export default Home;
